### ISSUE TITLE
Problem with the V2 install guide

### ISSUE THREAD

**Issue by jerabaul29** [nigelb/platform-apollo3blue#11]
In the Core_V2 installation guide, in the readme, this part:

```
~> cd ~/.platformio
~/.platformio> cd platforms
~/.platformio/platforms> git clone https://github.com/nigelb/platform-apollo3blue.git apollo3blue
```

I suppose there is a missing step at the end, checking out the actual Core_V2 branch of this repo, right? :

```
git checkout Core_V2
```

**Comment by nigelb** [comment]
Thank @jerabaul29 I have fixed that now.
