### ISSUE TITLE
Add ability to set swo clock in swo viewer

### ISSUE THREAD

**Issue by fariouche** [nigelb/platform-apollo3blue#44]
Hello,

My application is configured using the default ambiq swo clock of 1Mbauds and the autodetect seems to not work (it tries to set it to 12M
-swofreq 1000000 works for me

Thanks!

**Comment by nigelb** [comment]
Hi @fariouche ,

You can now add:

    board_debug.swo_freq=1000000

to your `platform.ini` file. Give it a whirl and let me know how you go.

**Comment by fariouche** [comment]
oh, it works! thanks!
I see you also added the option in the board json too!

**Comment by fariouche** [comment]
if you can have also a look at the other issue https://github.com/nigelb/platform-apollo3blue/issues/43, that would be perfect. This is the only patch I have remaining!
